/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteRpaArgs } from "./DeleteRpaArgs";
import { RpaFindManyArgs } from "./RpaFindManyArgs";
import { RpaFindUniqueArgs } from "./RpaFindUniqueArgs";
import { Rpa } from "./Rpa";
import { RpaService } from "../rpa.service";

@graphql.Resolver(() => Rpa)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class RpaResolverBase {
  constructor(
    protected readonly service: RpaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Rpa",
    action: "read",
    possession: "any",
  })
  async _rpasMeta(
    @graphql.Args() args: RpaFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Rpa])
  @nestAccessControl.UseRoles({
    resource: "Rpa",
    action: "read",
    possession: "any",
  })
  async rpas(@graphql.Args() args: RpaFindManyArgs): Promise<Rpa[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Rpa, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Rpa",
    action: "read",
    possession: "own",
  })
  async rpa(@graphql.Args() args: RpaFindUniqueArgs): Promise<Rpa | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Rpa)
  @nestAccessControl.UseRoles({
    resource: "Rpa",
    action: "delete",
    possession: "any",
  })
  async deleteRpa(@graphql.Args() args: DeleteRpaArgs): Promise<Rpa | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
